### ISSUE TITLE
Kiota python generator produces methods that fail on error responses

### ISSUE THREAD

**Issue by mikekistler** [microsoft/kiota-http-python#32]
Using the Kiota Python generator as described in microsoft/kiota#1996, after fixing the indentation problems manually, I'm getting exceptions from the Kiota httpx_request_adapter.py when the service returns a non-success response. Here's the traceback:

```
>>> tests = asyncio.run(client.loadtests().sort_and_filter().get(config))
Headers({'host': '6e856190-1a06-44bd-b3eb-4b51ec508b2f.southcentralus.cnt-prod.loadtesting.azure.com', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'user-agent': 'python-httpx/0.23.1', 'accept': 'application/json', 'authorization': '[secure]', 'request_options': '{}'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/mikekistler/Projects/mikekistler/kiota/client/loadtests/sort_and_filter/sort_and_filter_request_builder.py", line 67, in get
    return await self.request_adapter.send_async(request_info, test_model_resource_list.TestModelResourceList, response_handler, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/kiota_http/httpx_request_adapter.py", line 118, in send_async
    await self.throw_failed_responses(response, error_map)
  File "/opt/homebrew/lib/python3.11/site-packages/kiota_http/httpx_request_adapter.py", line 290, in throw_failed_responses
    in error_map) and not (400 <= status_code < 500 and error_map['4XX']
                                                        ~~~~~~~~~^^^^^^^
TypeError: 'NoneType' object is not subscriptable
>>> 
```

It shows that the problem is an attempt to subscript `error_map` which is `None`.

Here's the m`sort_and_filter().get()` method that Kiota generated:
```
async def get(self,request_configuration: Optional[SortAndFilterRequestBuilderGetRequestConfiguration] = None, response_handler: Optional[ResponseHandler] = None) -> Optional[test_model_resource_list.TestModelResourceList]:
    request_info = self.create_get_request_information(
        request_configuration
    )
    if not self.request_adapter:
        raise Exception("Http core is null") 
    return await self.request_adapter.send_async(request_info, test_model_resource_list.TestModelResourceList, response_handler, None)
```

The final `None`  in the `send_async` call is the `error_map`.

The responses for this operation in the REST API definition are:
```
        "responses": {
          "200": {
            "description": "The requested load tests",
            "schema": {
              "$ref": "#/definitions/TestModelResourceList"
            }
          },
          "default": {
            "description": "Load Testing service error response.",
            "schema": {
              "$ref": "#/definitions/ErrorResponseBody"
            },
            "headers": {
              "x-ms-error-code": {
                "description": "The error code for specific error that occurred.",
                "type": "string"
              }
            }
          }
        },
```

I suspect that the problem here is that Kiota is looking for 400 or 500 class responses and finding none, so passes an None as the error map.  But Azure uses `default` to describe error responses.

**Comment by baywet** [comment]
Thanks for reporting this. The code should check whether the map is none before trying to access it.
Transferred it to the right repo. And assigned to @samwelkanda.

**Comment by baywet** [comment]
for the default response this was a design choice, kiota ignores it. Having a default response in the description doesn't help anybody from a code-gen perspective: we don't know if this is meant for a successful response or a failed one. That means we'd have to make an opiniated choice and be wrong half the time.
You can instead use class responses (4XX, 5XX) and components to maximize re-use of the definitions.

**Comment by mikekistler** [comment]
I can't use class responses in OpenAPI v2 -- they were not added to OpenAPI until v3.

And while I respect your right to make design choices I would just say that this is an unfortunate one as it will preclude the use of Kiota for any Azure services.

**Comment by baywet** [comment]
Does Azure have any plan to upgrade the descriptions to v3 to take advantage of new capabilities?
