### ISSUE TITLE
Underlying HTTP client is closed after first request, causing subsequent requests to fail

### ISSUE THREAD

**Issue by jasonjoh** [microsoft/kiota-http-python#36]
Using the Python Graph SDK, I found this issue. The first request sent through the `GraphServiceClient` succeeds, but subsequent requests throw an exception:

```
Traceback (most recent call last):
  File "/home/jasonjoh/repos/msgraph-training-python/demo/graphtutorial/repro.py", line 17, in <module>
    users2 = asyncio.run(client.users().get())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/jasonjoh/.local/lib/python3.10/site-packages/msgraph/generated/users/users_request_builder.py", line 129, in get
    return await self.request_adapter.send_async(request_info, user_collection_response.UserCollectionResponse, response_handler, error_mapping)
  File "/home/jasonjoh/.local/lib/python3.10/site-packages/kiota_http/httpx_request_adapter.py", line 114, in send_async
    response = await self.get_http_response_message(request_info)
  File "/home/jasonjoh/.local/lib/python3.10/site-packages/kiota_http/httpx_request_adapter.py", line 329, in get_http_response_message
    resp = await self._http_client.send(request)
  File "/home/jasonjoh/.local/lib/python3.10/site-packages/httpx/_client.py", line 1609, in send
    raise RuntimeError("Cannot send a request, as the client has been closed.")
RuntimeError: Cannot send a request, as the client has been closed.
```

This seems to be caused by the following line:
https://github.com/microsoft/kiota-http-python/blob/d57aaedc0924cbabc50ca85cd69336510c5058ac/kiota_http/httpx_request_adapter.py#L330

This script can reproduce the problem:

```python
import asyncio
from azure.identity.aio import ClientSecretCredential
from kiota_authentication_azure.azure_identity_authentication_provider import AzureIdentityAuthenticationProvider
from msgraph import GraphRequestAdapter, GraphServiceClient

credential = ClientSecretCredential(
    'TENANT_ID',
    'CLIENT_ID',
    'CLIENT_SECRET')
auth_provider = AzureIdentityAuthenticationProvider(credential)
adapter = GraphRequestAdapter(auth_provider)
client = GraphServiceClient(adapter)

users = asyncio.run(client.users().get())
print('got users')

users2 = asyncio.run(client.users().get())
print('got users again')
```

**Comment by baywet** [comment]
@jasonjoh thanks for reporting this.
@samwelkanda I think you meant to close the response, not the client there, could you take a look at it please?

**Comment by samwelkanda** [comment]
Thank you for reporting this issue @jason. 

On a side note, to make the most of the async client, if you have multiple calls to the API, it's better to define a function that will execute them asynchronously, reusing the existing client and speeding up your application.
```py
async def get_users():
        users1 = await client.users().get()
        users2 = await client.users().get()
        print(users1)
        print(users2)
asyncio.run(get_users())
```
The above wi
